/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoetsIndexRouteImport } from './routes/poets/index'
import { Route as PoemsIndexRouteImport } from './routes/poems/index'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as PoetsPoetsIdIndexRouteImport } from './routes/poets/$poetsId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetsIndexRoute = PoetsIndexRouteImport.update({
  id: '/poets/',
  path: '/poets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIndexRoute = PoemsIndexRouteImport.update({
  id: '/poems/',
  path: '/poems/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetsPoetsIdIndexRoute = PoetsPoetsIdIndexRouteImport.update({
  id: '/poets/$poetsId/',
  path: '/poets/$poetsId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/contact': typeof ContactIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/poems': typeof PoemsIndexRoute
  '/poets': typeof PoetsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/poets/$poetsId': typeof PoetsPoetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/contact': typeof ContactIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/poems': typeof PoemsIndexRoute
  '/poets': typeof PoetsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/poets/$poetsId': typeof PoetsPoetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/poems/': typeof PoemsIndexRoute
  '/poets/': typeof PoetsIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/poets/$poetsId/': typeof PoetsPoetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/poems'
    | '/poets'
    | '/login'
    | '/register'
    | '/poets/$poetsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/poems'
    | '/poets'
    | '/login'
    | '/register'
    | '/poets/$poetsId'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/contact/'
    | '/features/'
    | '/poems/'
    | '/poets/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/poets/$poetsId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  PoemsIndexRoute: typeof PoemsIndexRoute
  PoetsIndexRoute: typeof PoetsIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  PoetsPoetsIdIndexRoute: typeof PoetsPoetsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poets/': {
      id: '/poets/'
      path: '/poets'
      fullPath: '/poets'
      preLoaderRoute: typeof PoetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/': {
      id: '/poems/'
      path: '/poems'
      fullPath: '/poems'
      preLoaderRoute: typeof PoemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poets/$poetsId/': {
      id: '/poets/$poetsId/'
      path: '/poets/$poetsId'
      fullPath: '/poets/$poetsId'
      preLoaderRoute: typeof PoetsPoetsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  PoemsIndexRoute: PoemsIndexRoute,
  PoetsIndexRoute: PoetsIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  PoetsPoetsIdIndexRoute: PoetsPoetsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
